In [1]:
#Author : Sayali Kudale

#loading the required libraries

import scipy.io
import numpy as np
import pandas as pd 
from sklearn.multiclass import OneVsRestClassifier 
from sklearn.svm import SVC 
from sklearn.metrics import accuracy_score, classification_report 
from sklearn.metrics import confusion_matrix  
import time

In [2]:
#Data Loading 

mat = scipy.io.loadmat('Data/USPS_all.mat')
df_features = pd.DataFrame(mat['fea'])
df_gnd = pd.DataFrame(mat['gnd'])


#Split data into training and testing set

train_fea= df_features.iloc[:7291] 
test_fea= df_features.iloc[-2007:]
train_dec= df_gnd.iloc[:7291] 
test_dec= df_gnd.iloc[-2007:] 

###  SVM Model - Linear Kernel 

In [3]:
# Creating the SVM model 
model = OneVsRestClassifier(SVC(kernel='linear')) 

trainStart = time.time()
# Fitting the model with training data 
model.fit(train_fea, train_dec) 

trainEnd = time.time()

print("Training time : ", trainEnd-trainStart)


Training time :  15.076912879943848


In [4]:
# Making a prediction on the test set 
prediction = model.predict(test_fea) 

In [5]:
# Evaluating the model 
score=accuracy_score(test_dec, prediction) * 100
print("Accuracy Score : %s" %score)

Accuracy Score : 91.6292974589


In [6]:
classsification_report=classification_report(test_dec, prediction)
print('Classification report for linear kernel function: \n',classsification_report)

cm_linear= confusion_matrix(test_dec, prediction)  
print("Confusion Matrix for linear kernel function: \n",cm_linear)

Classification report for linear kernel function: 
              precision    recall  f1-score   support

          1       0.95      0.97      0.96       359
          2       0.98      0.97      0.98       264
          3       0.87      0.85      0.86       198
          4       0.86      0.86      0.86       166
          5       0.86      0.89      0.87       200
          6       0.89      0.89      0.89       160
          7       0.96      0.95      0.96       170
          8       0.93      0.90      0.92       147
          9       0.88      0.87      0.87       166
         10       0.91      0.93      0.92       177

avg / total       0.92      0.92      0.92      2007

Confusion Matrix for linear kernel function: 
 [[350   0   2   1   3   0   0   0   3   0]
 [  0 255   1   3   2   0   2   0   1   0]
 [  5   0 168   6   9   1   1   2   6   0]
 [  2   0   4 142   2   8   0   3   3   2]
 [  1   2   7   0 177   1   2   2   3   5]
 [  3   0   0   7   3 143   0   0   0   4]
 [  

### SVM Model - Polynomial Kernel function

In [7]:
# Creating the SVM model 
modelPoly = OneVsRestClassifier(SVC(kernel='poly')) 
trainStart = time.time()
# Fitting the model with training data 
modelPoly.fit(train_fea, train_dec) 
trainEnd = time.time()

print("Training time : ", trainEnd-trainStart)


Training time :  16.43656301498413


In [8]:
# Making a prediction on the test set 
predictionPoly = modelPoly.predict(test_fea) 

In [9]:
# Evaluating the model 
scorePoly=accuracy_score(test_dec, predictionPoly) * 100
print("Accuracy Score : %s" %scorePoly)

Accuracy Score : 93.2735426009


In [10]:
classsification_reportPoly=classification_report(test_dec, predictionPoly)
print('Classification report of Polynomial kernel function: \n',classsification_reportPoly)

cm_poly= confusion_matrix(test_dec, predictionPoly)  
print("Confusion Matrix for Polynomial kernel function: \n",cm_poly)

Classification report of Polynomial kernel function: 
              precision    recall  f1-score   support

          1       0.94      0.99      0.96       359
          2       0.98      0.97      0.98       264
          3       0.90      0.89      0.90       198
          4       0.92      0.90      0.91       166
          5       0.88      0.93      0.90       200
          6       0.90      0.91      0.90       160
          7       0.96      0.92      0.94       170
          8       0.96      0.91      0.94       147
          9       0.94      0.88      0.91       166
         10       0.93      0.95      0.94       177

avg / total       0.93      0.93      0.93      2007

Confusion Matrix for Polynomial kernel function: 
 [[354   0   2   0   2   0   0   0   0   1]
 [  0 255   1   1   4   0   3   0   0   0]
 [  6   0 177   3   5   2   1   1   3   0]
 [  3   0   4 149   0   6   0   2   1   1]
 [  1   2   6   0 185   0   2   1   0   3]
 [  5   0   0   4   1 146   0   0   0   